import { Extension, ExtensionCategory } from "@/types";

export const extensionCatalog: Extension[] = [
  // AI Tools
  {
    id: "github-copilot",
    name: "GitHub Copilot",
    displayName: "GitHub Copilot",
    description: "Your AI pair programmer. Get suggestions for whole lines or entire blocks directly in your editor.",
    version: "1.234.0",
    publisher: "GitHub",
    category: "ai-tools",
    rating: 4.8,
    downloadCount: 15000000,
    installed: false,
    enabled: true,
    latestVersion: "1.234.0",
    permissions: ["editor:read", "editor:write", "network:access"],
    activationEvents: ["onLanguage", "onCommand"],
    updatedAt: "2024-01-15",
  },
  {
    id: "codeium",
    name: "Codeium",
    displayName: "Codeium: AI Autocomplete",
    description: "Free AI-powered autocomplete tool. Supercharge your coding with intelligent suggestions.",
    version: "2.1.5",
    publisher: "Codeium",
    category: "ai-tools",
    rating: 4.7,
    downloadCount: 3500000,
    installed: false,
    enabled: true,
    latestVersion: "2.1.5",
    permissions: ["editor:read", "editor:write", "network:access"],
    activationEvents: ["onLanguage"],
    updatedAt: "2024-01-10",
  },
  {
    id: "tabnine",
    name: "Tabnine",
    displayName: "Tabnine AI Code Assistant",
    description: "AI code completion tool trained on your team's code. Accelerate development.",
    version: "3.89.0",
    publisher: "Tabnine",
    category: "ai-tools",
    rating: 4.6,
    downloadCount: 2800000,
    installed: false,
    enabled: true,
    latestVersion: "3.89.0",
    permissions: ["editor:read", "editor:write", "network:access"],
    activationEvents: ["onLanguage"],
    updatedAt: "2024-01-12",
  },

  // Themes
  {
    id: "one-dark-pro",
    name: "One Dark Pro",
    displayName: "One Dark Pro",
    description: "Atom's iconic One Dark theme. The most installed theme in VS Code.",
    version: "3.16.0",
    publisher: "binaryify",
    category: "themes",
    rating: 4.9,
    downloadCount: 8500000,
    installed: false,
    enabled: true,
    latestVersion: "3.16.0",
    permissions: [],
    activationEvents: [],
    contributes: {
      themes: [{ id: "one-dark-pro", label: "One Dark Pro" }]
    },
    updatedAt: "2024-01-08",
  },
  {
    id: "dracula",
    name: "Dracula",
    displayName: "Dracula Official",
    description: "Official Dracula Theme. Dark theme for over 300 apps.",
    version: "2.24.3",
    publisher: "Dracula",
    category: "themes",
    rating: 4.8,
    downloadCount: 5200000,
    installed: false,
    enabled: true,
    latestVersion: "2.24.3",
    permissions: [],
    activationEvents: [],
    contributes: {
      themes: [{ id: "dracula", label: "Dracula" }]
    },
    updatedAt: "2024-01-05",
  },
  {
    id: "material-theme",
    name: "Material Theme",
    displayName: "Material Theme",
    description: "The most epic theme for Visual Studio Code.",
    version: "34.8.0",
    publisher: "Mattia Astorino",
    category: "themes",
    rating: 4.7,
    downloadCount: 4100000,
    installed: false,
    enabled: true,
    latestVersion: "34.8.0",
    permissions: [],
    activationEvents: [],
    contributes: {
      themes: [
        { id: "material-theme", label: "Material Theme" },
        { id: "material-theme-darker", label: "Material Theme Darker" },
        { id: "material-theme-ocean", label: "Material Theme Ocean" }
      ]
    },
    updatedAt: "2024-01-11",
  },
  {
    id: "nord",
    name: "Nord",
    displayName: "Nord",
    description: "An arctic, north-bluish clean and elegant theme.",
    version: "0.19.0",
    publisher: "arcticicestudio",
    category: "themes",
    rating: 4.8,
    downloadCount: 3900000,
    installed: false,
    enabled: true,
    latestVersion: "0.19.0",
    permissions: [],
    activationEvents: [],
    contributes: {
      themes: [{ id: "nord", label: "Nord" }]
    },
    updatedAt: "2024-01-03",
  },

  // Language Support
  {
    id: "python",
    name: "Python",
    displayName: "Python",
    description: "IntelliSense, Linting, Debugging, Jupyter Notebooks, Code Navigation, Code Formatting for Python.",
    version: "2024.0.1",
    publisher: "Microsoft",
    category: "language-support",
    rating: 4.7,
    downloadCount: 95000000,
    installed: false,
    enabled: true,
    latestVersion: "2024.0.1",
    permissions: ["editor:read", "filesystem:read", "terminal:execute"],
    activationEvents: ["onLanguage:python"],
    contributes: {
      languages: [{ id: "python", name: "Python" }]
    },
    updatedAt: "2024-01-14",
  },
  {
    id: "java",
    name: "Java",
    displayName: "Java Extension Pack",
    description: "Popular extensions for Java development including debugger, Maven support, and more.",
    version: "1.28.0",
    publisher: "Microsoft",
    category: "language-support",
    rating: 4.6,
    downloadCount: 42000000,
    installed: false,
    enabled: true,
    latestVersion: "1.28.0",
    permissions: ["editor:read", "filesystem:read", "terminal:execute"],
    activationEvents: ["onLanguage:java"],
    contributes: {
      languages: [{ id: "java", name: "Java" }]
    },
    updatedAt: "2024-01-13",
  },
  {
    id: "cpp",
    name: "C++",
    displayName: "C/C++",
    description: "C/C++ IntelliSense, debugging, and code browsing.",
    version: "1.19.6",
    publisher: "Microsoft",
    category: "language-support",
    rating: 4.5,
    downloadCount: 38000000,
    installed: false,
    enabled: true,
    latestVersion: "1.19.6",
    permissions: ["editor:read", "filesystem:read"],
    activationEvents: ["onLanguage:cpp", "onLanguage:c"],
    contributes: {
      languages: [
        { id: "cpp", name: "C++" },
        { id: "c", name: "C" }
      ]
    },
    updatedAt: "2024-01-09",
  },
  {
    id: "go",
    name: "Go",
    displayName: "Go",
    description: "Rich Go language support including IntelliSense, code navigation, and debugging.",
    version: "0.40.0",
    publisher: "Go Team at Google",
    category: "language-support",
    rating: 4.7,
    downloadCount: 18000000,
    installed: false,
    enabled: true,
    latestVersion: "0.40.0",
    permissions: ["editor:read", "filesystem:read", "terminal:execute"],
    activationEvents: ["onLanguage:go"],
    contributes: {
      languages: [{ id: "go", name: "Go" }]
    },
    updatedAt: "2024-01-11",
  },
  {
    id: "rust",
    name: "Rust",
    displayName: "rust-analyzer",
    description: "Rust language support. Provides type inference and completions.",
    version: "0.3.1832",
    publisher: "rust-lang",
    category: "language-support",
    rating: 4.8,
    downloadCount: 8500000,
    installed: false,
    enabled: true,
    latestVersion: "0.3.1832",
    permissions: ["editor:read", "filesystem:read"],
    activationEvents: ["onLanguage:rust"],
    contributes: {
      languages: [{ id: "rust", name: "Rust" }]
    },
    updatedAt: "2024-01-15",
  },

  // Code Formatters
  {
    id: "prettier",
    name: "Prettier",
    displayName: "Prettier - Code formatter",
    description: "Code formatter using prettier. Supports JavaScript, TypeScript, CSS, HTML, and more.",
    version: "10.1.0",
    publisher: "Prettier",
    category: "code-formatters",
    rating: 4.9,
    downloadCount: 45000000,
    installed: false,
    enabled: true,
    latestVersion: "10.1.0",
    permissions: ["editor:read", "editor:write"],
    activationEvents: ["onLanguage"],
    updatedAt: "2024-01-12",
  },

  // Linters
  {
    id: "eslint",
    name: "ESLint",
    displayName: "ESLint",
    description: "Integrates ESLint JavaScript into VS Code. Find and fix problems in your code.",
    version: "3.0.10",
    publisher: "Microsoft",
    category: "linters",
    rating: 4.8,
    downloadCount: 38000000,
    installed: false,
    enabled: true,
    latestVersion: "3.0.10",
    permissions: ["editor:read", "filesystem:read"],
    activationEvents: ["onLanguage:javascript", "onLanguage:typescript"],
    updatedAt: "2024-01-10",
  },

  // Git Tools
  {
    id: "gitlens",
    name: "GitLens",
    displayName: "GitLens — Git supercharged",
    description: "Supercharge Git within VS Code. Visualize code authorship, navigate repositories.",
    version: "2024.1.1",
    publisher: "GitKraken",
    category: "git-tools",
    rating: 4.8,
    downloadCount: 28000000,
    installed: false,
    enabled: true,
    latestVersion: "2024.1.1",
    permissions: ["filesystem:read", "editor:read"],
    activationEvents: ["onCommand"],
    updatedAt: "2024-01-14",
  },

  // Database Tools
  {
    id: "database-client",
    name: "Database Client",
    displayName: "Database Client",
    description: "Database client for PostgreSQL, MySQL, SQLite, Redis, MongoDB and more.",
    version: "5.7.2",
    publisher: "cweijan",
    category: "database-tools",
    rating: 4.6,
    downloadCount: 5200000,
    installed: false,
    enabled: true,
    latestVersion: "5.7.2",
    permissions: ["network:access", "filesystem:read", "filesystem:write"],
    activationEvents: ["onCommand"],
    updatedAt: "2024-01-08",
  },

  // Docker Tools
  {
    id: "docker",
    name: "Docker",
    displayName: "Docker",
    description: "Makes it easy to create, manage, and debug containerized applications.",
    version: "1.29.0",
    publisher: "Microsoft",
    category: "docker-tools",
    rating: 4.7,
    downloadCount: 22000000,
    installed: false,
    enabled: true,
    latestVersion: "1.29.0",
    permissions: ["terminal:execute", "filesystem:read"],
    activationEvents: ["onCommand"],
    updatedAt: "2024-01-13",
  },

  // Testing Tools
  {
    id: "jest-runner",
    name: "Jest Runner",
    displayName: "Jest Runner",
    description: "Run jest test from context menu or view gutter.",
    version: "0.4.69",
    publisher: "firsttris",
    category: "testing-tools",
    rating: 4.5,
    downloadCount: 3800000,
    installed: false,
    enabled: true,
    latestVersion: "0.4.69",
    permissions: ["terminal:execute", "editor:read"],
    activationEvents: ["onLanguage:javascript", "onLanguage:typescript"],
    updatedAt: "2024-01-07",
  },

  // Productivity Tools
  {
    id: "todo-tree",
    name: "Todo Tree",
    displayName: "Todo Tree",
    description: "Show TODO, FIXME, and other comments in a tree view.",
    version: "0.0.226",
    publisher: "Gruntfuggly",
    category: "productivity-tools",
    rating: 4.7,
    downloadCount: 6500000,
    installed: false,
    enabled: true,
    latestVersion: "0.0.226",
    permissions: ["editor:read", "filesystem:read"],
    activationEvents: ["onStartupFinished"],
    updatedAt: "2024-01-06",
  },
  {
    id: "tailwind-css",
    name: "Tailwind CSS IntelliSense",
    displayName: "Tailwind CSS IntelliSense",
    description: "Intelligent Tailwind CSS tooling. Autocomplete, syntax highlighting, and linting.",
    version: "0.12.3",
    publisher: "Tailwind Labs",
    category: "productivity-tools",
    rating: 4.8,
    downloadCount: 9200000,
    installed: false,
    enabled: true,
    latestVersion: "0.12.3",
    permissions: ["editor:read"],
    activationEvents: ["onLanguage"],
    updatedAt: "2024-01-11",
  },
];
